# Generated by Django 4.2.16 on 2024-11-13 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_remustar', '0002_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='id_business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_remustar.business'),
        ),
    ]
