# Generated by Django 4.2.16 on 2024-11-14 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_remustar', '0003_customuser_id_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
