# Generated by Django 4.2.16 on 2024-11-14 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_remustar', '0004_alter_business_description_alter_business_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='owner',
        ),
    ]
