# Generated by Django 4.2.16 on 2024-11-19 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_remustar', '0007_bankaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('business_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_remustar.business')),
            ],
        ),
    ]
