# Generated by Django 4.2.16 on 2024-11-19 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_remustar', '0008_businessmeta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
