# Generated by Django 4.2.16 on 2024-11-19 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_remustar', '0009_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='commune',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
