# Generated by Django 4.2.16 on 2024-11-19 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_remustar', '0010_business_commune'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
