# Generated by Django 4.2.16 on 2024-12-10 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_remustar', '0011_business_province_business_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id_business',
            field=models.ForeignKey(blank=True, db_column='business_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_remustar.business'),
        ),
    ]
